export interface StreakConfig {
  id: number;
  baseRotate: string;
  left: string;
  width: string;
  height: string;
  bottom: string;
  colorVar: string;
  colorPercent: string;
  animationType: "a" | "b";
  animationDuration: string;
  animationDelay: string;
  clipPath?: string;
}

export const STREAK_DATA: StreakConfig[] = [
  {
    id: 1,
    baseRotate: "-30deg",
    left: "5%",
    width: "8%",
    height: "28%",
    bottom: "-2%",
    colorVar: "--space-left-glow",
    colorPercent: "60%",
    animationType: "a",
    animationDuration: "12s",
    animationDelay: "-0s",
  },
  {
    id: 2,
    baseRotate: "-25deg",
    left: "11%",
    width: "7%",
    height: "32%",
    bottom: "-4%",
    colorVar: "--space-left-glow",
    colorPercent: "40%",
    animationType: "b",
    animationDuration: "15s",
    animationDelay: "-4s",
  },
  {
    id: 3,
    baseRotate: "-20deg",
    left: "17%",
    width: "10%",
    height: "38%",
    bottom: "-6%",
    colorVar: "--space-left-glow",
    colorPercent: "50%",
    animationType: "a",
    animationDuration: "11s",
    animationDelay: "-2s",
  },
  {
    id: 4,
    baseRotate: "-15deg",
    left: "23%",
    width: "8%",
    height: "44%",
    bottom: "-8%",
    colorVar: "--space-left-glow",
    colorPercent: "65%",
    animationType: "b",
    animationDuration: "14s",
    animationDelay: "-6s",
  },
  {
    id: 5,
    baseRotate: "-10deg",
    left: "29%",
    width: "9%",
    height: "48%",
    bottom: "-10%",
    colorVar: "--space-center-glow",
    colorPercent: "55%",
    animationType: "a",
    animationDuration: "16s",
    animationDelay: "-3s",
  },
  {
    id: 6,
    baseRotate: "-6deg",
    left: "34%",
    width: "12%",
    height: "56%",
    bottom: "-15%",
    colorVar: "--space-center-glow",
    colorPercent: "45%",
    animationType: "b",
    animationDuration: "13s",
    animationDelay: "-8s",
  },
  {
    id: 7,
    baseRotate: "-3deg",
    left: "36.5%",
    width: "10%",
    height: "62%",
    bottom: "-18%",
    colorVar: "--space-center-glow",
    colorPercent: "60%",
    animationType: "a",
    animationDuration: "17s",
    animationDelay: "-5s",
    clipPath: "polygon(35% 0, 65% 0, 100% 100%, 0 100%)",
  },
  {
    id: 8,
    baseRotate: "-1deg",
    left: "40%",
    width: "14%",
    height: "68%",
    bottom: "-22%",
    colorVar: "--space-center-glow",
    colorPercent: "50%",
    animationType: "b",
    animationDuration: "11s",
    animationDelay: "-1s",
    clipPath: "polygon(40% 0, 60% 0, 100% 100%, 0 100%)",
  },
  {
    id: 9,
    baseRotate: "0deg",
    left: "45.5%",
    width: "14%",
    height: "72%",
    bottom: "-24%",
    colorVar: "--space-center-glow",
    colorPercent: "65%",
    animationType: "a",
    animationDuration: "15s",
    animationDelay: "-7s",
    clipPath: "polygon(42% 0, 58% 0, 100% 100%, 0 100%)",
  },
  {
    id: 10,
    baseRotate: "2deg",
    left: "51.5%",
    width: "14%",
    height: "66%",
    bottom: "-22%",
    colorVar: "--space-center-glow",
    colorPercent: "50%",
    animationType: "b",
    animationDuration: "12s",
    animationDelay: "-3s",
    clipPath: "polygon(40% 0, 60% 0, 100% 100%, 0 100%)",
  },
  {
    id: 11,
    baseRotate: "5deg",
    left: "58.5%",
    width: "10%",
    height: "58%",
    bottom: "-18%",
    colorVar: "--space-center-glow",
    colorPercent: "55%",
    animationType: "a",
    animationDuration: "18s",
    animationDelay: "-9s",
    clipPath: "polygon(35% 0, 65% 0, 100% 100%, 0 100%)",
  },
  {
    id: 12,
    baseRotate: "9deg",
    left: "67%",
    width: "13%",
    height: "50%",
    bottom: "-15%",
    colorVar: "--space-right-glow",
    colorPercent: "45%",
    animationType: "b",
    animationDuration: "14s",
    animationDelay: "-2s",
  },
  {
    id: 13,
    baseRotate: "14deg",
    left: "72%",
    width: "8%",
    height: "46%",
    bottom: "-10%",
    colorVar: "--space-right-glow",
    colorPercent: "60%",
    animationType: "a",
    animationDuration: "11s",
    animationDelay: "-5s",
  },
  {
    id: 14,
    baseRotate: "19deg",
    left: "78%",
    width: "9%",
    height: "40%",
    bottom: "-8%",
    colorVar: "--space-right-glow",
    colorPercent: "40%",
    animationType: "b",
    animationDuration: "16s",
    animationDelay: "-7s",
  },
  {
    id: 15,
    baseRotate: "24deg",
    left: "84%",
    width: "10%",
    height: "34%",
    bottom: "-6%",
    colorVar: "--space-right-glow",
    colorPercent: "50%",
    animationType: "a",
    animationDuration: "13s",
    animationDelay: "-4s",
  },
  {
    id: 16,
    baseRotate: "30deg",
    left: "90%",
    width: "7%",
    height: "30%",
    bottom: "-2%",
    colorVar: "--space-right-glow",
    colorPercent: "60%",
    animationType: "b",
    animationDuration: "10s",
    animationDelay: "-1s",
  },
];
